### ISSUE TITLE
An Error when stop the service while touching it or moving it!

### ISSUE THREAD

**Issue by khaledkhj** [recruit-lifestyle/FloatingView#39] opened 2017-04-12 05:30 UTC
Any way to handle this error?
Error: "FloatingView not attached to window manager"

**Comment by khaledkhj** [comment] 2017-04-12 05:34
it happened here 
at jp.co.recruit_lifestyle.android.floatingview.FloatingView$FloatingAnimationHandler.handleMessage(FloatingView.java:921)

**Comment by YoshihideSogawa** [comment] 2017-04-12 06:00
I understood the place where the error occurred.
However, it seems that it is causing errors outside the scope of FloatingView library.
Perhaps it seems to be caused by a class (calling FloatingViewManager.addViewToWindow) like [ChatHeadService](https://github.com/recruit-lifestyle/FloatingView/blob/master/sample/src/main/java/jp/co/recruit_lifestyle/sample/service/ChatHeadService.java).
Please provide more detailed source code and log if detailed information is needed.

**Comment by khaledkhj** [comment] 2017-04-12 07:28
java.lang.IllegalArgumentException: View=jp.co.recruit_lifestyle.android.floatingview.FloatingView{8063126 V.E..... ......ID 0,0-133,133} not attached to window manager
                                                                      at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:412)
                                                                      at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:324)
                                                                      at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:97)
                                                                      at jp.co.recruit_lifestyle.android.floatingview.FloatingView$FloatingAnimationHandler.handleMessage(FloatingView.java:1051)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:145)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6939)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by khaledkhj** [comment] 2017-04-12 07:30
I am doing it exactly the same way of  [ChatHeadService.java](https://github.com/recruit-lifestyle/FloatingView/blob/master/sample/src/main/java/jp/co/recruit_lifestyle/sample/service/ChatHeadService.java)

**Comment by YoshihideSogawa** [comment] 2017-04-12 08:10
Does an error also occur when using the original of FloatingView's sample?

**Comment by khaledkhj** [comment] 2017-04-12 08:13
yes is does

**Comment by khaledkhj** [comment] 2017-04-12 08:14
here is how I am try to avoid this, at least for now

`view = (RelativeLayout) inflater.inflate(R.layout.chathead_layout, null, false);
 view.getRootView().setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent event) {

                switch(event.getAction()) {
                    case MotionEvent.ACTION_DOWN:
                        canStop = false;
                        break;

                    case MotionEvent.ACTION_MOVE:
                        canStop = false;
                        break;

                    case MotionEvent.ACTION_UP:
                        canStop = true;

                        if (shouldStop){
                            stopSelf();
                        }
                        break;
                }

                return true;
            }
        });`

**Comment by YoshihideSogawa** [comment] 2017-04-12 08:17
Thank you for your information.
What is the name and version of the Android device you used?

**Comment by khaledkhj** [comment] 2017-04-12 08:20
you are welcome

Device: Samsung Tab A6
Android: V5.1.1

**Comment by YoshihideSogawa** [comment] 2017-04-13 01:18
Since I don’t have this device and the solution method has not been found yet.
Also, the cause of this error is not known.
Do you have special settings on an Android device?

**Comment by khaledkhj** [comment] 2017-04-13 08:06
No, there is not!

**Comment by YoshihideSogawa** [comment] 2017-04-13 08:18
Mmm...
Which are checked in Developer options setting of Android device?

**Comment by khaledkhj** [comment] 2017-04-13 10:56
I am not really sure if this effects, 
but I only have USB debugging and verify Apps via USB which are enabled.

**Comment by YoshihideSogawa** [comment] 2017-06-22 06:25
Please check whether the same bug occurs on[ ver 2.2.2-alpha](https://github.com/recruit-lifestyle/FloatingView/releases/tag/2.2.2-alpha).

`compile 'com.github.recruit-lifestyle:FloatingView:2.2.2-alpha'`

**Comment by YoshihideSogawa** [comment] 2017-06-27 09:11
Waiting for 2.2.2

**Comment by YoshihideSogawa** [comment] 2017-07-19 08:28
Fixed [2.2.2](https://github.com/recruit-lifestyle/FloatingView/releases/tag/2.2.2)

**Closed by YoshihideSogawa** 2017-07-19 08:28 UTC
Labels: bug
